### ISSUE TITLE
What does this plugin do?

### ISSUE THREAD

**Issue by Faisalthe01** [SynTexDZN/homebridge-syntex-tuya#1]
What does this plugin do?

**Comment by SynTexDZN** [comment]
It‘s a plugin currently in beta to control Tuya / Smart Life Devices via HomeHit. Stay tuned for some updates to the README and the public release. At the moment only outlets are supported :)

**Comment by Faisalthe01** [comment]
Great. Thank you. Hope it won’t be incomplete like the original Homebridge-Tuya-Web. Would you be able to fix things that were not working correctly in original like, Color Mode and Brightness for Bulbs and add Garage Door too. Cheers

**Comment by SynTexDZN** [comment]
I try to because I got many tuya bulbs from different labels. The difficulty is that the tuyawebapi response doesn‘t contain data about the hue. State and brightness are shown correctly but I think the problem with the hue relates to the API server. I will do my best to expand the support or to create a new firmware to flash the devices with tuya-convert. Beta testers for devices I doesn‘t actually own (like Garage Door accessory) are always recommended :)

**Comment by SynTexDZN** [comment]
Just to ask because of the way you comment. Do you speak german? Because you often write words starting with big letters what Germans often do 😇

**Comment by Faisalthe01** [comment]
Nah sorry I don’t but i do have a 6 years old German Shepherd lol. Anyway, good to see your plugin is in progress. I am currently using Tuya Web fork by Vitramir, he fixed the Brightness in his plug in but couldn’t fix hue or garage door.

**Comment by SynTexDZN** [comment]
Brightness Service is now also implemented
